**Page Rank Algorithm**

Importing libraries

In [1]:
'''
Name: Khan Arshad Abdulla
Roll No: 20CO24
'''

import numpy as np
from fractions import Fraction

To get output in float format

In [2]:
def display_format(my_vector, my_decimal):
    return np.round((my_vector).astype(np.float64), decimals=my_decimal)

Setting Default probablity

In [3]:
my_dp = Fraction(1,3)


Creating the Matrix

In [4]:
Mat = np.matrix([[0, Fraction(1, 2), Fraction(1, 2)],
        [0, 0, 1],
        [1, 0, 0]])

In [5]:
Mat = np.transpose(Mat)

In [6]:
Mat

matrix([[0, 0, 1],
        [Fraction(1, 2), 0, 0],
        [Fraction(1, 2), 1, 0]], dtype=object)

Creating the default probability matrix

In [7]:
E = np.zeros((3,3))
E[:] = my_dp

In [8]:
E

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

Setting damping factor

In [9]:
df = 0.7

#Page rank
Al = ((1-df) * E) + df * Mat

In [10]:
Al

matrix([[0.1, 0.1, 0.7999999999999999],
        [0.44999999999999996, 0.1, 0.1],
        [0.44999999999999996, 0.7999999999999999, 0.1]], dtype=object)

Create next iteration matrix and take transpose of it

In [11]:
r = np.matrix([1, 1, 1])
r = np.transpose(r)
r

matrix([[1],
        [1],
        [1]])

Iterate the matrix

In [12]:
previous_r = r

for i in range(1,100):
    r = Al * r
    print (display_format(r,3))
    if (previous_r==r).all():
        break

[[1.  ]
 [0.65]
 [1.35]]
[[1.245]
 [0.65 ]
 [1.105]]
[[1.074]
 [0.736]
 [1.191]]
[[1.134]
 [0.676]
 [1.191]]
[[1.134]
 [0.697]
 [1.17 ]]
[[1.119]
 [0.697]
 [1.184]]
[[1.129]
 [0.692]
 [1.179]]
[[1.126]
 [0.695]
 [1.179]]
[[1.126]
 [0.694]
 [1.181]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.18 ]]
[[1.126]
 [0.694]
 [1.1

In [13]:
print ("Final:\n", display_format(r,3))

Final:
 [[1.126]
 [0.694]
 [1.18 ]]


In [14]:
print ("Sum: ", np.sum(r))

Sum:  2.9999999999999867
